sudo: required
dist: trusty

install:
  - pip install -r requirements.txt

before_script:
  - pip install -U pip
  - pip-compile --dry-run requirements.in | diff -u requirements.txt -

script:
  - bash -xve ./test/travis_ros_install.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_package_make.bash
